name: CompatHelper
on:
  schedule:
    - cron: '0 0 * * *' # Checks daily
  workflow_dispatch: # Manual trigger
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
      - uses: JuliaRegistries/CompatHelper.jl@v3
        with:
          token: ${{ secrets.GH_PAT }}
